# Generated by Django 2.2 on 2022-01-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('location', models.TextField(null=True)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('latin_name', models.CharField(max_length=45)),
                ('sun', models.CharField(max_length=45)),
                ('water', models.CharField(max_length=255)),
                ('spacing', models.IntegerField()),
                ('days_to_harvest', models.IntegerField()),
                ('pH', models.FloatField()),
                ('soil_reqs', models.TextField(null=True)),
                ('planting', models.TextField(null=True)),
                ('companion_plants', models.TextField(null=True)),
                ('dont_plant_near', models.TextField(null=True)),
                ('pruning', models.TextField(null=True)),
                ('harvesting', models.TextField(null=True)),
                ('common_pests', models.TextField(null=True)),
                ('medicinal_props', models.TextField(null=True)),
                ('edibility', models.TextField(null=True)),
                ('other_uses', models.TextField(null=True)),
                ('specific_notes', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users_growing', models.ManyToManyField(related_name='growing_plant', to='portfolio.User')),
            ],
        ),
    ]
