# Generated by Django 2.2 on 2022-01-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='users_growing',
            field=models.ManyToManyField(related_name='growing_plants', to='portfolio.User'),
        ),
    ]
