# Generated by Django 2.2 on 2022-01-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20220127_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='family',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
