# Generated by Django 2.2 on 2022-02-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_plant_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='height_width',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
