# Generated by Django 2.2 on 2022-02-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_plant_height_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='users_growing',
        ),
        migrations.AddField(
            model_name='plant',
            name='user_likes',
            field=models.ManyToManyField(related_name='plants_liked', to='portfolio.User'),
        ),
    ]
