# Generated by Django 2.2 on 2022-02-03 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20220203_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='user_likes',
            new_name='users_like',
        ),
    ]
