# Generated by Django 2.2 on 2022-02-21 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20220218_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user_note',
            new_name='written_by',
        ),
    ]
