# Generated by Django 2.2 on 2022-02-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20220221_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='written_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_written', to='portfolio.User'),
        ),
    ]
