# Generated by Django 2.2 on 2022-03-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20220224_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('source', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('supplies', models.TextField()),
                ('total_yield', models.CharField(max_length=45)),
                ('active_time', models.CharField(max_length=45)),
                ('passive_time', models.CharField(max_length=45)),
                ('instructions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
