# Generated by Django 2.2 on 2022-03-03 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='written_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes_written', to='portfolio.User'),
        ),
    ]
