# Generated by Django 2.2 on 2022-03-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_recipe_written_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='when_to_start',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
