# Generated by Django 2.2 on 2022-03-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_plant_when_to_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='transplant_or_ds',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
