# Generated by Django 2.2 on 2022-03-18 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_plant_transplant_or_ds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='when_to_start',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='planting',
            new_name='succession_planting',
        ),
    ]
