# Generated by Django 2.2 on 2022-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
